name: tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        java: ['17', '18', '19']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}

      - uses: DeLaGuardo/setup-clojure@10.0
        with:
          lein: latest

      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: ~/.m2/repository
          key: deps-${{ hashFiles('project.clj') }}

      - run: lein test-all
